<?php
vc_map(array(
	"name" => esc_html__("Countdown", 'ruya'),
	"base" => "countdown",
	"category" => esc_html__('Extra Elements', 'ruya'),
    "icon" => "tb-icon-for-vc fa fa-hourglass-end",
	"class" => "bt_countdown",
	"params" => array(
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("Style", 'ruya'),
			"param_name" => "style",
			"value" => array(
				"Style 1" => "style1",
				"Style 2" => "style2",
				"Style 3" => "style3",
			),
			"description" => esc_html__('Select style in this elment.', 'ruya')
		),
	    array(
			"type" => "textfield",
			"heading" => esc_html__("Date count down",'ruya'),
			"param_name" => "date_count_down",
			"value" => "",
	        "admin_label" => true,
			"description" => esc_html__("Set date count down (default:2019/10/10)",'ruya'),
		 ),
	    array(
		    "type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("Position", 'ruya'),
			"param_name" => "position",
			"value" => array(
				"center" => "text-center",
				"right" => "text-right",
				"left" => "text-left",
			),
		),
	    array(
            'type' => 'dropdown',
            'heading' => esc_html__( 'Animation CSS', 'ruya' ),
            'value' => array(
	            esc_html__( 'none', 'ruya' )          => 'none',
                esc_html__( 'bounceIn', 'ruya' )      => 'wow bounceIn',
                esc_html__( 'bounceInDown', 'ruya' )  => 'wow bounceInDown',
                esc_html__( 'bounceInLeft', 'ruya' )  => 'wow bounceInLeft',
			    esc_html__( 'bounceInRight', 'ruya' ) => 'wow bounceInRight',
			    esc_html__( 'bounceInUp', 'ruya' )    => 'wow bounceInUp',
			    esc_html__( 'fadeIn', 'ruya' )        => 'wow fadeIn',
			    esc_html__( 'fadeInDown', 'ruya' )    => 'wow fadeInDown',
			    esc_html__( 'fadeInDownBig', 'ruya' ) => 'wow fadeInDownBig',
			    esc_html__( 'fadeInLeft', 'ruya' )    => 'wow fadeInLeft',
			    esc_html__( 'fadeInLeftBig', 'ruya' ) => 'wow fadeInLeftBig',
			    esc_html__( 'fadeInRight', 'ruya' )   => 'wow fadeInRight',
			    esc_html__( 'fadeInRightBig', 'ruya' )=> 'wow fadeInRightBig',
			    esc_html__( 'fadeInUp', 'ruya' )      => 'wow fadeInUp',
			    esc_html__( 'fadeInUpBig', 'ruya' )   => 'wow fadeInUpBig',
			    esc_html__( 'flipInX', 'ruya' )       => 'wow flipInX',
			    esc_html__( 'flipInY', 'ruya' )       => 'wow flipInY',
                esc_html__( 'slideInUp', 'ruya' )     => 'wow slideInUp',
                esc_html__( 'slideInDown', 'ruya' )   => 'wow slideInDown',
			    esc_html__( 'slideInLeft', 'ruya' )   => 'wow slideInLeft',
			    esc_html__( 'slideInRight', 'ruya' )  => 'wow slideInRight',
			    esc_html__( 'zoomIn', 'ruya' )        => 'wow zoomIn',
			    esc_html__( 'zoomInDown', 'ruya' )    => 'wow zoomInDown',
			    esc_html__( 'zoomInLeft', 'ruya' )    => 'wow zoomInLeft',
			    esc_html__( 'zoomInRight', 'ruya' )   => 'wow zoomInRight',
			    esc_html__( 'zoomInUp', 'ruya' )      => 'wow zoomInUp',
            ),
            'param_name' => 'animation_css',
            'description' => esc_html__( 'Select animation type.', 'ruya' ),
        ),
	    array(
            'type' => 'dropdown',
            'heading' => esc_html__( 'Animation Delay', 'ruya' ),
            'value' => array(
                esc_html__( '0.1s', 'ruya' ) => '0.1s',
                esc_html__( '0.2s', 'ruya' ) => '0.2s',
                esc_html__( '0.3s', 'ruya' ) => '0.3s',
	            esc_html__( '0.4s', 'ruya' ) => '0.4s',
                esc_html__( '0.5s', 'ruya' ) => '0.5s',
                esc_html__( '0.6s', 'ruya' ) => '0.6s',
                esc_html__( '0.7s', 'ruya' ) => '0.7s',
	            esc_html__( '0.8s', 'ruya' ) => '0.8s',
                esc_html__( '0.9s', 'ruya' ) => '0.9s',
            ),
            'param_name' => 'animation_delay',
		    'description' => esc_html__( 'Select animation delay.', 'ruya' ),
        ),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => esc_html__("Extra Class", 'ruya'),
			"param_name" => "el_class",
			"value" => "",
			"description" => esc_html__ ( "If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 'ruya' )
		),
	)
));
