<?php
vc_map(array(
	"name" => esc_html__("Fancy Heading", 'ruya'),
	"base" => "fancy_heading",
	"category" => esc_html__('Extra Elements', 'ruya'),
    "icon" => "tb-icon-for-vc fa fa-list",
	"params" => array(
		   array(
				"type" => "textfield",
				'heading'     => esc_html__( 'Title', 'ruya' ),
				'param_name'  => 'title',
				'admin_label' => true,
			),
	        array(
				'type'        => 'vc_link',
				'heading'     => esc_html__( 'URL (Link)', 'ruya' ),
				'param_name'  => 'link',
				'description' => esc_html__( 'Add link to custom heading.', 'ruya' ),
			),
	      //Typo Options
	       array(
				'type' => 'colorpicker',
				'only_solid' => true,
				'param_name' => 'color',
				'heading'     => esc_html__( 'Color', 'ruya' ),
	            'description' => esc_html__( 'Defalut: #000', 'ruya' ),
	            'edit_field_class' => 'vc_col-sm-3',
	            'group' => esc_html__( 'Style', 'ruya' ),
			),
			array(
				'type'        => 'textfield',
				'param_name'  => 'font_size',
				'heading'     => esc_html__( 'Font Size', 'ruya' ),
				'description' => esc_html__( 'Defalut: 36px', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
				'group' => esc_html__( 'Style', 'ruya' ),
			),
			array(
				'type'        => 'textfield',
				'param_name'  => 'line_height',
				'heading'     => esc_html__( 'Line-Height', 'ruya' ),
	            'description' => esc_html__( 'Defalut: 42px', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
				'group' => esc_html__( 'Style', 'ruya' ),
			),
	        array(
				'type'        => 'textfield',
				'param_name'  => 'letter_spacing',
				'heading'     => esc_html__( 'Letter Spacing', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
				'group' => esc_html__( 'Style', 'ruya' ),
			),
	        array(
				'type'        => 'dropdown',
				'param_name'  => 'alignment',
				'heading'     => esc_html__( 'Alignment', 'ruya' ),
				'value'       => array(
					esc_html__( 'Inherit', 'ruya' )   => '',
					esc_html__( 'Left', 'ruya' )      => 'left',
					esc_html__( 'Center', 'ruya' )    => 'center',
					esc_html__( 'Right', 'ruya' )     => 'right'
				),
				'edit_field_class' => 'vc_col-sm-3',
	            'group' => esc_html__( 'Style', 'ruya' ),
			),
	        array(
				'type'        => 'dropdown',
				'param_name'  => 'font_weight',
				'heading'     => esc_html__( 'Font Weight', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'value'      => array(
					esc_html__( 'Normal', 'ruya' )=> '400',
					esc_html__( 'Thick', 'ruya' ) => '600',
					esc_html__( 'Bold', 'ruya' )  => '700',
					esc_html__( 'Bolder', 'ruya' )=> '900',
				),
	            'std' => '700',
				'group' => esc_html__( 'Style', 'ruya' ),
			),
			array(
				'type'       => 'dropdown',
				'param_name' => 'text_transform',
				'heading'    => esc_html__( 'Transformation', 'ruya' ),
				'value'      => array(
					esc_html__( 'Default', 'ruya' )    => '',
					esc_html__( 'Uppercase', 'ruya' )  => 'uppercase',
					esc_html__( 'Lowercase', 'ruya' )  => 'lowercase',
					esc_html__( 'Capitalize', 'ruya' ) => 'capitalize',
				),
				'edit_field_class' => 'vc_col-sm-3',
	            'group' => esc_html__( 'Style', 'ruya' ),
			),
			array(
				'type'       => 'dropdown',
				'param_name' => 'underline',
				'heading'    => esc_html__( 'Underline', 'ruya' ),
				'value'      => array(
					esc_html__( 'No', 'ruya' )  => '',
					esc_html__( 'Yes', 'ruya' ) => 'underline',
				),
				'edit_field_class' => 'vc_col-sm-3',
	            'group' => esc_html__( 'Style', 'ruya' ),
			),
			
	       //Rotator
			array(
				'type'        => 'checkbox',
				'param_name'  => 'enable_txt_rotator',
				'heading'     => esc_html__( 'Enable Text Rotator?', 'ruya' ),
				'description' => esc_html__( 'Check to enable text rotator', 'ruya' ),
				'value'       => array( esc_html__( 'Yes', 'ruya' ) => 'yes'  ),
	            'group' => __( 'Rotator', 'ruya' ),
			),
	        array(
				'type' => 'param_group',
				'heading'    => esc_html__( 'Separated words for text rotator', 'ruya' ),
				'param_name' => 'words',
				'description' => esc_html__( 'Enter values for list item', 'ruya' ),
				'value'      => '',
	            'group' => __( 'Rotator', 'ruya' ),
				'params'     => array(
					array(
						'type'        => 'textfield',
						'param_name'  => 'word',
						'heading'     => esc_html__( 'Title word', 'ruya' ),
						'description' => esc_html__( 'Add word for title rotator', 'ruya' ),
						'admin_label' => true,
					),
				),
				'dependency' => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
	         array(
				'type' => 'dropdown',
				'heading' => __( 'In Animation (effect)','ruya' ),
				'param_name' => 'in_animate_effect',
				'value' => array('flash' => 'flash', 'bounce' => 'bounce', 'shake' => 'shake', 'tada' => 'tada', 'swing' => 'swing', 'wobble' => 'wobble', 'pulse' => 'pulse', 'flip' => 'flip', 'flipInX' => 'flipInX', 'flipOutX' => 'flipOutX', 'flipInY' => 'flipInY', 'flipOutY' => 'flipOutY', 'fadeIn' => 'fadeIn', 'fadeInUp' => 'fadeInUp', 'fadeInDown' => 'fadeInDown', 'fadeInLeft' => 'fadeInLeft', 'fadeInRight' => 'fadeInRight', 'fadeInUpBig' => 'fadeInUpBig', 'fadeInDownBig' => 'fadeInDownBig', 'fadeInLeftBig' => 'fadeInLeftBig', 'fadeInRightBig' => 'fadeInRightBig', 'fadeOut' => 'fadeOut', 'fadeOutUp' => 'fadeOutUp', 'fadeOutDown' => 'fadeOutDown', 'fadeOutLeft' => 'fadeOutLeft', 'fadeOutRight' => 'fadeOutRight', 'fadeOutUpBig' => 'fadeOutUpBig', 'fadeOutDownBig' => 'fadeOutDownBig', 'fadeOutLeftBig' => 'fadeOutLeftBig', 'fadeOutRightBig' => 'fadeOutRightBig', 'bounceIn' => 'bounceIn', 'bounceInDown' => 'bounceInDown', 'bounceInUp' => 'bounceInUp', 'bounceInLeft' => 'bounceInLeft', 'bounceInRight' => 'bounceInRight', 'bounceOut' => 'bounceOut', 'bounceOutDown' => 'bounceOutDown', 'bounceOutUp' => 'bounceOutUp', 'bounceOutLeft' => 'bounceOutLeft', 'bounceOutRight' => 'bounceOutRight', 'rotateIn' => 'rotateIn', 'rotateInDownLeft' => 'rotateInDownLeft', 'rotateInDownRight' => 'rotateInDownRight', 'rotateInUpLeft' => 'rotateInUpLeft', 'rotateInUpRight' => 'rotateInUpRight', 'rotateOut' => 'rotateOut', 'rotateOutDownLeft' => 'rotateOutDownLeft', 'rotateOutDownRight' => 'rotateOutDownRight', 'rotateOutUpLeft' => 'rotateOutUpLeft', 'rotateOutUpRight' => 'rotateOutUpRight', 'hinge' => 'hinge', 'rollIn' => 'rollIn', 'rollOut' => 'rollOut'),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'In Animation (type)','ruya' ),
				'param_name' => 'in_animate_type',
				'value' => array( 'sequence' => '', 'reverse' => 'reverse', 'sync' => 'sync', 'shuffle' => 'shuffle' ),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'Out Animation (effect)','ruya' ),
				'param_name' => 'out_animate_effect',
				'value' => array('flash' => 'flash', 'bounce' => 'bounce', 'shake' => 'shake', 'tada' => 'tada', 'swing' => 'swing', 'wobble' => 'wobble', 'pulse' => 'pulse', 'flip' => 'flip', 'flipInX' => 'flipInX', 'flipOutX' => 'flipOutX', 'flipInY' => 'flipInY', 'flipOutY' => 'flipOutY', 'fadeIn' => 'fadeIn', 'fadeInUp' => 'fadeInUp', 'fadeInDown' => 'fadeInDown', 'fadeInLeft' => 'fadeInLeft', 'fadeInRight' => 'fadeInRight', 'fadeInUpBig' => 'fadeInUpBig', 'fadeInDownBig' => 'fadeInDownBig', 'fadeInLeftBig' => 'fadeInLeftBig', 'fadeInRightBig' => 'fadeInRightBig', 'fadeOut' => 'fadeOut', 'fadeOutUp' => 'fadeOutUp', 'fadeOutDown' => 'fadeOutDown', 'fadeOutLeft' => 'fadeOutLeft', 'fadeOutRight' => 'fadeOutRight', 'fadeOutUpBig' => 'fadeOutUpBig', 'fadeOutDownBig' => 'fadeOutDownBig', 'fadeOutLeftBig' => 'fadeOutLeftBig', 'fadeOutRightBig' => 'fadeOutRightBig', 'bounceIn' => 'bounceIn', 'bounceInDown' => 'bounceInDown', 'bounceInUp' => 'bounceInUp', 'bounceInLeft' => 'bounceInLeft', 'bounceInRight' => 'bounceInRight', 'bounceOut' => 'bounceOut', 'bounceOutDown' => 'bounceOutDown', 'bounceOutUp' => 'bounceOutUp', 'bounceOutLeft' => 'bounceOutLeft', 'bounceOutRight' => 'bounceOutRight', 'rotateIn' => 'rotateIn', 'rotateInDownLeft' => 'rotateInDownLeft', 'rotateInDownRight' => 'rotateInDownRight', 'rotateInUpLeft' => 'rotateInUpLeft', 'rotateInUpRight' => 'rotateInUpRight', 'rotateOut' => 'rotateOut', 'rotateOutDownLeft' => 'rotateOutDownLeft', 'rotateOutDownRight' => 'rotateOutDownRight', 'rotateOutUpLeft' => 'rotateOutUpLeft', 'rotateOutUpRight' => 'rotateOutUpRight', 'hinge' => 'hinge', 'rollIn' => 'rollIn', 'rollOut' => 'rollOut'),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'Out Animation (type)','ruya' ),
				'param_name' => 'out_animate_type',
				'value' => array( 'sequence' => '', 'reverse' => 'reverse', 'sync' => 'sync', 'shuffle' => 'shuffle' ),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'textfield',
				'heading' => __( 'initialDelay','ruya' ),
				'param_name' => 'initial_delay',
				'value' => 0,
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'autoStart','ruya' ),
				'param_name' => 'auto_start',
				'value' => array( 'True' => 1, 'False' => 0 ),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'loop','ruya' ),
				'param_name' => 'loop',
				'value' => array( 'True' => 1, 'False' => 0 ),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
			array(
				'type' => 'dropdown',
				'heading' => __( 'type','ruya' ),
				'param_name' => 'type',
				'value' => array( 'char' => 'char', 'word' => 'word' ),
				'description' => __( '','ruya' ),
				'group' => __( 'Rotator', 'ruya' ),
				'edit_field_class' => 'vc_col-sm-3',
	            'dependency'  => array(
					'element' => 'enable_txt_rotator',
					'value'   => 'yes',
				),
			),
	
			//Animation Options
	        //split
			array(
				'type'        => 'checkbox',
				'param_name'  => 'enable_split',
				'heading'     => esc_html__( 'Enable Split?', 'ruya' ),
				'description' => esc_html__( 'Check to enable split effect', 'ruya' ),
	            'group'            => esc_html__( 'Animation', 'ruya' ),
			),
			array(
				'type' => 'dropdown',
				'param_name' => 'split_type',
				'heading'     => esc_html__( 'Split Type', 'ruya' ),
				'description' => esc_html__( 'Select split type', 'ruya' ),
				'value'       => array(
	               esc_html__( 'Words', 'ruya' ) => 'words',
	               esc_html__( 'Characters', 'ruya' ) => 'chars, words',
				),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	           'edit_field_class' => 'vc_col-sm-4',
	           'std'              =>  'words',
	           'group'            => esc_html__( 'Animation', 'ruya' ),
			),
	        array(
				'type'        => 'dropdown',
				'param_name'  => 'easing',
				'heading'     => esc_html__( 'Easing', 'ruya' ),
				'description' => esc_html__( 'Select an easing type', 'ruya' ),
				'value'       => array(
					'easeInQuad',
					'easeInCubic',
					'easeInQuart',
					'easeInQuint',
					'easeInSine',
					'easeInExpo',
					'easeInCirc',
					'easeInBack',
					'easeOutQuad',
					'easeOutCubic',
					'easeOutQuart',
					'easeOutQuint',
					'easeOutSine',
					'easeOutExpo',
					'easeOutCirc',
					'easeOutBack',
					'easeInOutQuad',
					'easeInOutCubic',
					'easeInOutQuart',
					'easeInOutQuint',
					'easeInOutSine',
					'easeInOutExpo',
					'easeInOutCirc',
					'easeInOutBack',
					'linear',
				),
				'std'         => 'easeInQuad',
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
				'group'            => esc_html__( 'Animation', 'ruya' ),
			),
	        array(
				'type'        => 'dropdown',
				'param_name'  => 'direction',
				'heading'     => esc_html__( 'Direction', 'ruya' ),
				'description' => esc_html__( 'Select animations direction', 'ruya' ),
				'value'       => array(
					esc_html__( 'Forward', 'ruya' )  => 'forward',
					esc_html__( 'Backward', 'ruya' ) => 'backward',
				),
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
				'group' => esc_html__( 'Animation', 'ruya' ),
			),
			array(
				'type'        => 'textfield',
				'param_name'  => 'duration',
				'heading'     => esc_html__( 'Duration', 'ruya' ),
				'description' => esc_html__( 'Add duration of the animation in milliseconds Default: 1200', 'ruya' ),
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
				'group'            => esc_html__( 'Animation', 'ruya' ),
			),
			array(
				'type'        => 'textfield',
				'param_name'  => 'start_delay',
				'heading'     => esc_html__( 'Start Delay', 'ruya' ),
				'description' => esc_html__( 'Add start delay of the animation in milliseconds', 'ruya' ),
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
				'group'            => esc_html__( 'Animation', 'ruya' ),
			),
			array(
				'type'        => 'textfield',
				'param_name'  => 'delay',
				'heading'     => esc_html__( 'Delay', 'ruya' ),
				'description' => esc_html__( 'Add delay of the animation between of the animated elements in milliseconds Default: 120', 'ruya' ),
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
				'group'            => esc_html__( 'Animation', 'ruya' ),
			),
			
			array(
				'type'        => 'subheading',
				'param_name'  => 'ca_init_values',
				'heading'     => esc_html__( 'Animate From', 'ruya' ),
				'group'       => esc_html__( 'Animation', 'ruya' ),
				'dependency'  => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_translate_x',
				'heading'     => esc_html__( 'Translate X', 'ruya' ),
				'description' => esc_html__( 'Select translate on X axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	           'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_translate_y',
				'heading'     => esc_html__( 'Translate Y', 'ruya' ),
				'description' => esc_html__( 'Select translate on Y axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_translate_z',
				'heading'     => esc_html__( 'Translate Z', 'ruya' ),
				'description' => esc_html__( 'Select translate on Z axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_scale_x',
				'heading'     => esc_html__( 'Scale X', 'ruya' ),
				'description' => esc_html__( 'Select Scale X', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_scale_y',
				'heading'     => esc_html__( 'Scale Y', 'ruya' ),
				'description' => esc_html__( 'Select Scale Y', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_scale_z',
				'heading'     => esc_html__( 'Scale Z', 'ruya' ),
				'description' => esc_html__( 'Select Scale Z', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_rotate_x',
				'heading'     => esc_html__( 'Rotate X', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on X axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	           'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_rotate_y',
				'heading'     => esc_html__( 'Rotate Y', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on Y axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_rotate_z',
				'heading'     => esc_html__( 'Rotate Z', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on Z axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_init_opacity',
				'heading'     => esc_html__( 'Opacity', 'ruya' ),
				'description' => esc_html__( 'Set opacity', 'ruya' ),
				'min'         => 0,
				'max'         => 1,
				'step'        => 0.1,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-11',
			),
			
			//Animation Values
			array(
				'type'        => 'subheading',
				'param_name'  => 'ca_animations_values',
				'heading'     => esc_html__( 'Animate To', 'ruya' ),
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
			),			
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_translate_x',
				'heading'     => esc_html__( 'Translate X', 'ruya' ),
				'description' => esc_html__( 'Select translate on X axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_translate_y',
				'heading'     => esc_html__( 'Translate Y', 'ruya' ),
				'description' => esc_html__( 'Select translate on Y axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_translate_z',
				'heading'     => esc_html__( 'Translate Z', 'ruya' ),
				'description' => esc_html__( 'Select translate on Z axe', 'ruya' ),
				'min'         => -500,
				'max'         => 500,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_scale_x',
				'heading'     => esc_html__( 'Scale X', 'ruya' ),
				'description' => esc_html__( 'Select Scale X', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_scale_y',
				'heading'     => esc_html__( 'Scale Y', 'ruya' ),
				'description' => esc_html__( 'Select Scale Y', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_scale_z',
				'heading'     => esc_html__( 'Scale Z', 'ruya' ),
				'description' => esc_html__( 'Select Scale Z', 'ruya' ),
				'min'         => 0,
				'max'         => 10,
				'step'        => 0.25,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
				'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_rotate_x',
				'heading'     => esc_html__( 'Rotate X', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on X axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_rotate_y',
				'heading'     => esc_html__( 'Rotate Y', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on Y axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_rotate_z',
				'heading'     => esc_html__( 'Rotate Z', 'ruya' ),
				'description' => esc_html__( 'Select rotate degree on Z axe', 'ruya' ),
				'min'         => -360,
				'max'         => 360,
				'step'        => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-4',
			),
			array(
				'type'        => 'mo_slider',
				'param_name'  => 'ca_an_opacity',
				'heading'     => esc_html__( 'Opacity', 'ruya' ),
				'description' => esc_html__( 'Set opacity', 'ruya' ),
				'min'         => 0,
				'max'         => 1,
				'step'        => 0.1,
				'std'         => 1,
				'group' => esc_html__( 'Animation', 'ruya' ),
				'dependency' => array(
					'element' => 'enable_split',
					'value'   => 'true',
				),
	            'edit_field_class' => 'vc_col-sm-11',
			),
	)
));