<?php
$url = RUYA_URI . '/assets/img/portfolio/';
vc_map ( array (
	"name" => 'Portfolio grid',
	"base" => "portfolio_grid",
    "icon" => "tb-icon-for-vc fa fa-file-image-o",
	"category" => esc_html__( 'Extra Elements', 'ruya' ), 
	"params" => array (
	    array(
				"type" => "dropdown",
				"class" => "",
				"heading" => esc_html__("Template", 'ruya'),
				"param_name" => "tpl",
	            "admin_label" => true,
				"value" => array(
					"Portfolio style 1" => "grid",
					"Portfolio style 2" => "grid2",
					"Portfolio style 3" => "grid3",
                	"Portfolio style 4" => "grid4",
				),
	            "group"      => esc_html__("Style", 'ruya'),
	  	),
	    array(
				'type'	     => 'image_select',
				'heading'	 => '',
				'param_name' => 'style_image1',
	            'value'      => $url . 'style1.jpg',
				'dependency' => Array('element' => "tpl", 'value' => array('grid')),
				"group"      => esc_html__("Style", 'ruya'),
		),
	    array(
				'type'	     => 'image_select',
				'heading'	 => '',
				'param_name' => 'style_image2',
			    'value'      => $url . 'style2.jpg',
				'dependency' => Array('element' => "tpl", 'value' => array('grid2')),
				"group"      => esc_html__("Style", 'ruya'),
		),
	    array(
				'type'	     => 'image_select',
				'heading'	 => '',
				'param_name' => 'style_image3',
			    'value'      => $url . 'style3.jpg',
				'dependency' => Array('element' => "tpl", 'value' => array('grid3')),
				"group"      => esc_html__("Style", 'ruya'),
		),
	   array(
				'type'	     => 'image_select',
				'heading'	 => '',
				'param_name' => 'style_image4',
			    'value'      => $url . 'style4.jpg',
				'dependency' => Array('element' => "tpl", 'value' => array('grid4')),
				"group"      => esc_html__("Style", 'ruya'),
		),
	    array(
			"type" => "dropdown",
			"heading" => esc_html__("Show Filter OR Hide", 'ruya'),
			"param_name" => "show_filter",
			"value" => array(
				"True"   => "true",
				"False"  => "false",
			),
		),
		array(
			"type"      => "textfield",
			"class"     => "",
			"heading"   => esc_html__("Keyword for All Filter", 'ruya'),
			"param_name"=> "all_filter",
			"value"     => "All",
			"description" => esc_html__("Replace the default \"All\" keyword for the initial filter with another one.", 'ruya'),
	        'dependency'  => array(
	           "element" =>"show_filter",
	           "value"   => "true",
		    ),
	        'edit_field_class' => 'vc_col-sm-6',
        ),
	    array(
			"type" => "dropdown",
			"heading" => esc_html__("Filter alignment", 'ruya'),
			"param_name" => "align_filter",
			"value" => array(
				"Center" => "center",
				"Left"   => "left",
			    "Right"  => "right"
			),
	        'dependency'  => array(
	           "element" =>"show_filter",
	           "value"   => "true",
		    ),
		    'edit_field_class' => 'vc_col-sm-6',
		),
	    array(
			"type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("Image size", 'ruya'),
			"param_name" => "image_size",
			"value" => array(
					"Full"        => "full",
					"Medium"      => "ruya-medium",
					"Thumbnail"   => "thumbnail",
                	"Larg height" => "ruya-lg-height",
			),
	        "group" => esc_html__("Build Query", 'ruya'),
		),
	    array(
			"type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("Column", 'ruya'),
			"param_name" => "column",
			"value" => array(
	            "2 column" => "col-2",
				"3 column" => "col-3",
				"4 column" => "col-4",
				"5 column" => "col-5",
			),
	        'std'              => 'col-3',
			"group"            => esc_html__("Build Query", 'ruya'),
			"description"      => esc_html__('The number of column to display on portfolio page.', 'ruya'),
		    'edit_field_class' => 'vc_col-sm-4',
		),
		array (
			"type" => "textfield",
			"heading" => esc_html__( 'Count', 'ruya' ),
			"param_name" => "posts_per_page",
			'value' => '',
			"group" => esc_html__("Build Query", 'ruya'),
			"description" => esc_html__( 'The number of posts to display on each page. Set to "-1" for display all posts on the page.', 'ruya' ),
		    'edit_field_class' => 'vc_col-sm-4',
		),
	    array(
			"type" => "textfield",
			"class" => "",
			"heading" => esc_html__("margin", 'ruya'),
			"param_name" => "margin",
			"value" => "",
			"group" => esc_html__("Build Query", 'ruya'),
			"description" => esc_html__("Please, enter value in this element. Default: 5", 'ruya'),
		    'edit_field_class' => 'vc_col-sm-4',
		),
	    array(
			'type' => 'dropdown',
			'heading' => esc_html__('Type navigation', 'ruya'),
	        "group" => esc_html__("Build Query", 'ruya'),
			'description' => esc_html__('Select the type of navigation or disable it.', 'ruya'),
			'param_name' => 'typenavigation',
			'value' => array(
				"None" => 'none',
				"Prev/Next buttons" => 'buttons',
				"Numeric" => 'numeric',
			),
	        'edit_field_class' => 'vc_col-sm-4',
		),
		array (
			"type" => "dropdown",
			"heading" => esc_html__( 'Order by', 'ruya' ),
			"param_name" => "orderby",
			"value" => array (
					"None" => "none",
					"Title" => "title",
					"Date" => "date",
					"ID" => "ID"
			),
			"group" => esc_html__("Build Query", 'ruya'),
			"description" => esc_html__( 'Order by ("none", "title", "date", "ID").', 'ruya' ),
		    'edit_field_class' => 'vc_col-sm-4',
		),
		array (
			"type" => "dropdown",
			"heading" => esc_html__( 'Order', 'ruya' ),
			"param_name" => "order",
			"value" => Array (
					"None" => "none",
					"ASC" => "ASC",
					"DESC" => "DESC"
			),
			"group" => esc_html__("Build Query", 'ruya'),
			"description" => esc_html__( 'Order ("None", "Asc", "Desc").', 'ruya' ),
		    'edit_field_class' => 'vc_col-sm-4',
		),
	)
));