<?php
vc_map ( array (
	"name" => 'Textillate',
	"base" => "textillate",
    "icon" => "tb-icon-for-vc fa fa-text-width",
	"category" => esc_html__( 'Extra Elements', 'ruya' ), 
	"params" => array (
	 array(
		'type' => 'param_group',
		'heading' => esc_html__( 'Lists', 'ruya' ),
		'param_name' => 'list',
		'description' => esc_html__( 'Enter values for list item', 'ruya' ),
		'value' => urlencode(
			json_encode( array(
					array(
						'list_item' => '', 
					),
				) 
			) 
		),
		'params' => array(
			array(
				"type" => "textfield",
				"heading" =>esc_html__("List item",'ruya'),
				"param_name" => "list_item",
				'admin_label' => true,
			), 
		),
	),
  array(
		"type" => "textfield",
		"heading" =>esc_html__("Font Size",'ruya'),
		"param_name" => "fontsize",
		"description" => esc_html__("Please, add font size to in this element ex: 16px.", 'ruya'),
		'group' => __( 'Text', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
	),
	array(
		"type" => "textfield",
		"heading" =>esc_html__("Line Height",''),
		"param_name" => "lineheight",
		"description" => esc_html__("Please, add line height to in this element ex: 23px.", 'ruya'),
		'group' => __( 'Text', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
	),
	array(
		"type" => "dropdown",
		"heading" =>esc_html__("Text Align",''),
		"param_name" => "textalign",
		"value" => array(
			"Left"   => "left",
			"Center" => "center",
			"Right"  => "right",
		),
		"description" => esc_html__('Please, add text align to in this element', 'ruya'),
		'group' => __( 'Text', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
	),
	array(
		"type" => "dropdown",
		"heading" =>esc_html__("Font Weight",''),
		"param_name" => "fontweight",
        'value'      => array(
			esc_html__( 'Normal', 'ruya' )=> '400',
			esc_html__( 'Thick', 'ruya' ) => '600',
			esc_html__( 'Bold', 'ruya' )  => '700',
			esc_html__( 'Bolder', 'ruya' )=> '900',
		),
		"description" => esc_html__('Please, add font weight to in this element', 'ruya'),
	  	'group' => __( 'Text', 'ruya' ),
    	'edit_field_class' => 'vc_col-sm-6',
	),
   array(
		"type" => "colorpicker",
		"heading" =>esc_html__("List item Color",'ruya'),
		"param_name" => "color",
		'group' => __( 'Text', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
	),
	array(
		'type' => 'dropdown',
		'heading' => __( 'In Animation (effect)','ruya' ),
		'param_name' => 'in_animate_effect',
		'value' => array('flash' => 'flash', 'bounce' => 'bounce', 'shake' => 'shake', 'tada' => 'tada', 'swing' => 'swing', 'wobble' => 'wobble', 'pulse' => 'pulse', 'flip' => 'flip', 'flipInX' => 'flipInX', 'flipOutX' => 'flipOutX', 'flipInY' => 'flipInY', 'flipOutY' => 'flipOutY', 'fadeIn' => 'fadeIn', 'fadeInUp' => 'fadeInUp', 'fadeInDown' => 'fadeInDown', 'fadeInLeft' => 'fadeInLeft', 'fadeInRight' => 'fadeInRight', 'fadeInUpBig' => 'fadeInUpBig', 'fadeInDownBig' => 'fadeInDownBig', 'fadeInLeftBig' => 'fadeInLeftBig', 'fadeInRightBig' => 'fadeInRightBig', 'fadeOut' => 'fadeOut', 'fadeOutUp' => 'fadeOutUp', 'fadeOutDown' => 'fadeOutDown', 'fadeOutLeft' => 'fadeOutLeft', 'fadeOutRight' => 'fadeOutRight', 'fadeOutUpBig' => 'fadeOutUpBig', 'fadeOutDownBig' => 'fadeOutDownBig', 'fadeOutLeftBig' => 'fadeOutLeftBig', 'fadeOutRightBig' => 'fadeOutRightBig', 'bounceIn' => 'bounceIn', 'bounceInDown' => 'bounceInDown', 'bounceInUp' => 'bounceInUp', 'bounceInLeft' => 'bounceInLeft', 'bounceInRight' => 'bounceInRight', 'bounceOut' => 'bounceOut', 'bounceOutDown' => 'bounceOutDown', 'bounceOutUp' => 'bounceOutUp', 'bounceOutLeft' => 'bounceOutLeft', 'bounceOutRight' => 'bounceOutRight', 'rotateIn' => 'rotateIn', 'rotateInDownLeft' => 'rotateInDownLeft', 'rotateInDownRight' => 'rotateInDownRight', 'rotateInUpLeft' => 'rotateInUpLeft', 'rotateInUpRight' => 'rotateInUpRight', 'rotateOut' => 'rotateOut', 'rotateOutDownLeft' => 'rotateOutDownLeft', 'rotateOutDownRight' => 'rotateOutDownRight', 'rotateOutUpLeft' => 'rotateOutUpLeft', 'rotateOutUpRight' => 'rotateOutUpRight', 'hinge' => 'hinge', 'rollIn' => 'rollIn', 'rollOut' => 'rollOut'),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'In Animation (type)','ruya' ),
		'param_name' => 'in_animate_type',
		'value' => array( 'sequence' => '', 'reverse' => 'reverse', 'sync' => 'sync', 'shuffle' => 'shuffle' ),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'Out Animation (effect)','ruya' ),
		'param_name' => 'out_animate_effect',
		'value' => array('flash' => 'flash', 'bounce' => 'bounce', 'shake' => 'shake', 'tada' => 'tada', 'swing' => 'swing', 'wobble' => 'wobble', 'pulse' => 'pulse', 'flip' => 'flip', 'flipInX' => 'flipInX', 'flipOutX' => 'flipOutX', 'flipInY' => 'flipInY', 'flipOutY' => 'flipOutY', 'fadeIn' => 'fadeIn', 'fadeInUp' => 'fadeInUp', 'fadeInDown' => 'fadeInDown', 'fadeInLeft' => 'fadeInLeft', 'fadeInRight' => 'fadeInRight', 'fadeInUpBig' => 'fadeInUpBig', 'fadeInDownBig' => 'fadeInDownBig', 'fadeInLeftBig' => 'fadeInLeftBig', 'fadeInRightBig' => 'fadeInRightBig', 'fadeOut' => 'fadeOut', 'fadeOutUp' => 'fadeOutUp', 'fadeOutDown' => 'fadeOutDown', 'fadeOutLeft' => 'fadeOutLeft', 'fadeOutRight' => 'fadeOutRight', 'fadeOutUpBig' => 'fadeOutUpBig', 'fadeOutDownBig' => 'fadeOutDownBig', 'fadeOutLeftBig' => 'fadeOutLeftBig', 'fadeOutRightBig' => 'fadeOutRightBig', 'bounceIn' => 'bounceIn', 'bounceInDown' => 'bounceInDown', 'bounceInUp' => 'bounceInUp', 'bounceInLeft' => 'bounceInLeft', 'bounceInRight' => 'bounceInRight', 'bounceOut' => 'bounceOut', 'bounceOutDown' => 'bounceOutDown', 'bounceOutUp' => 'bounceOutUp', 'bounceOutLeft' => 'bounceOutLeft', 'bounceOutRight' => 'bounceOutRight', 'rotateIn' => 'rotateIn', 'rotateInDownLeft' => 'rotateInDownLeft', 'rotateInDownRight' => 'rotateInDownRight', 'rotateInUpLeft' => 'rotateInUpLeft', 'rotateInUpRight' => 'rotateInUpRight', 'rotateOut' => 'rotateOut', 'rotateOutDownLeft' => 'rotateOutDownLeft', 'rotateOutDownRight' => 'rotateOutDownRight', 'rotateOutUpLeft' => 'rotateOutUpLeft', 'rotateOutUpRight' => 'rotateOutUpRight', 'hinge' => 'hinge', 'rollIn' => 'rollIn', 'rollOut' => 'rollOut'),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'Out Animation (type)','ruya' ),
		'param_name' => 'out_animate_type',
		'value' => array( 'sequence' => '', 'reverse' => 'reverse', 'sync' => 'sync', 'shuffle' => 'shuffle' ),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-6',
		),
	array(
		'type' => 'textfield',
		'heading' => __( 'initialDelay','ruya' ),
		'param_name' => 'initial_delay',
		'value' => 0,
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-3',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'autoStart','ruya' ),
		'param_name' => 'auto_start',
		'value' => array( 'True' => 1, 'False' => 0 ),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-3',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'loop','ruya' ),
		'param_name' => 'loop',
		'value' => array( 'True' => 1, 'False' => 0 ),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-3',
		),
	array(
		'type' => 'dropdown',
		'heading' => __( 'type','ruya' ),
		'param_name' => 'type',
		'value' => array( 'char' => 'char', 'word' => 'word' ),
		'description' => __( '','ruya' ),
		'group' => __( 'Animation', 'ruya' ),
	    'edit_field_class' => 'vc_col-sm-3',
		),
	array(
		'type' => 'textfield',
		'heading' => __( 'Extra Class','ruya' ),
		'param_name' => 'class',
		'value' => '',
		'description' => __( '','ruya' ),
		),
	)
));