<?php
$url = RUYA_URI . '/assets/img/title-box/';
vc_map(array(
	"name" => esc_html__("Title Box", 'ruya'),
	"base" => "title_box",
	"category" => esc_html__('Extra Elements', 'ruya'),
	"icon" => "tb-icon-for-vc fa fa-server",
	"params" => array(
	   array(
			'type'       => 'select_preview',
			'param_name' => 'ruya_template',
			'heading'    => esc_html__('Style', 'ruya'),
	        'group'      => esc_html__("Template", 'ruya'),
			'value'      => array(
				array(
					'value' => 'title-box-style1',
					'label' => esc_html__('style1', 'ruya'),
					'image' => $url . 'style1.jpg'
				),
				array(
	                'value' => 'title-box-style2',
					'label' => esc_html__('style2', 'ruya'),
					'image' => $url . 'style2.jpg'
				),
				array(
	                'value' => 'title-box-style3',
					'label' => esc_html__('style3', 'ruya'),
					'image' => $url . 'style3.jpg'
				),
				array(
	                'value' => 'title-box-style4',
					'label' => esc_html__('style4', 'ruya'),
					'image' => $url . 'style4.jpg'
				),
	            array(
	                'value' => 'title-box-style5',
					'label' => esc_html__('style5', 'ruya'),
					'image' => $url . 'style5.jpg'
				),
	            array(
	                'value' => 'title-box-style6',
					'label' => esc_html__('style6', 'ruya'),
					'image' => $url . 'style6.jpg'
				),
			),
			'save_always' => true,
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => esc_html__("Title", 'ruya'),
			"param_name" => "title",
			"value" => "",
	        "admin_label" => true,
			"description" => esc_html__("Please, enter title in this element.", 'ruya')
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => esc_html__("Subtitle", 'ruya'),
			"param_name" => "subtitle",
			"value" => "",
			"description" => esc_html__("Please, enter subtitle in this element.", 'ruya')
		),
	     array(
			"type" => "textarea_html",
			"class" => "",
			"heading" => esc_html__("Description", 'ruya'),
			"param_name" => "content_box",
			"value" => "",
			"description" => esc_html__("Please, enter description in this element.", 'ruya'),
		),
		array(
		    "type" => "dropdown",
			"class" => "",
			"heading" => esc_html__("Title Position", 'ruya'),
			"param_name" => "position",
			"value" => array(
				"center" => "text-center",
				"right" => "text-right",
				"left" => "text-left",
			),
		),
	
		//Animation Options
	    array(
			'type'        => 'checkbox',
			'param_name'  => 'enable_split',
			'heading'     => esc_html__( 'Enable Split?', 'ruya' ),
			'description' => esc_html__( 'Check to enable split effect', 'ruya' ),
		    'group'            => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type' => 'dropdown',
			'param_name' => 'split_type',
			'heading'     => esc_html__( 'Split Type', 'ruya' ),
			'description' => esc_html__( 'Select split type', 'ruya' ),
			'value'       => array(
				esc_html__( 'Words', 'ruya' ) => 'words',
	            esc_html__( 'Characters', 'ruya' ) => 'chars, words',
			),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'group'            => esc_html__( 'Animation', 'ruya' ),
	        'edit_field_class' => 'vc_col-sm-6',
		),
	    array(
			'type'        => 'dropdown',
			'param_name'  => 'easing',
			'heading'     => esc_html__( 'Easing', 'ruya' ),
			'description' => esc_html__( 'Select an easing type', 'ruya' ),
			'value'       => array(
				'easeInQuad',
				'easeInCubic',
				'easeInQuart',
				'easeInQuint',
				'easeInSine',
				'easeInExpo',
				'easeInCirc',
				'easeInBack',
				'easeOutQuad',
				'easeOutCubic',
				'easeOutQuart',
				'easeOutQuint',
				'easeOutSine',
				'easeOutExpo',
				'easeOutCirc',
				'easeOutBack',
				'easeInOutQuad',
				'easeInOutCubic',
				'easeInOutQuart',
				'easeInOutQuint',
				'easeInOutSine',
				'easeInOutExpo',
				'easeInOutCirc',
				'easeInOutBack',
	            'linear',
			),
			'std'         => 'easeInQuad',
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type'        => 'textfield',
			'param_name'  => 'duration',
			'heading'     => esc_html__( 'Duration', 'ruya' ),
			'description' => esc_html__( 'Add duration of the animation in milliseconds Default:1200', 'ruya' ),
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
			'group'            => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type'        => 'textfield',
			'param_name'  => 'start_delay',
			'heading'     => esc_html__( 'Start Delay', 'ruya' ),
			'description' => esc_html__( 'Add start delay of the animation in milliseconds', 'ruya' ),
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type'        => 'textfield',
			'param_name'  => 'delay',
			'heading'     => esc_html__( 'Delay', 'ruya' ),
			'description' => esc_html__( 'Add delay of the animation between of the animated elements in milliseconds Default:120', 'ruya' ),
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type'        => 'dropdown',
			'param_name'  => 'direction',
			'heading'     => esc_html__( 'Direction', 'ruya' ),
			'description' => esc_html__( 'Select animations direction', 'ruya' ),
			'value'       => array(
				esc_html__( 'Forward', 'ruya' )  => 'forward',
				esc_html__( 'Backward', 'ruya' ) => 'backward',
			),
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-6',
			'group' => esc_html__( 'Animation', 'ruya' ),
		),
		array(
			'type'        => 'subheading',
			'param_name'  => 'ca_init_values',
			'heading'     => esc_html__( 'Animate From', 'ruya' ),
			'group'       => esc_html__( 'Animation', 'ruya' ),
			'dependency'  => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_translate_x',
			'heading'     => esc_html__( 'Translate X', 'ruya' ),
			'description' => esc_html__( 'Select translate on X axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		   'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_translate_y',
			'heading'     => esc_html__( 'Translate Y', 'ruya' ),
			'description' => esc_html__( 'Select translate on Y axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_translate_z',
			'heading'     => esc_html__( 'Translate Z', 'ruya' ),
			'description' => esc_html__( 'Select translate on Z axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_scale_x',
			'heading'     => esc_html__( 'Scale X', 'ruya' ),
			'description' => esc_html__( 'Select Scale X', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_scale_y',
			'heading'     => esc_html__( 'Scale Y', 'ruya' ),
			'description' => esc_html__( 'Select Scale Y', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_scale_z',
			'heading'     => esc_html__( 'Scale Z', 'ruya' ),
			'description' => esc_html__( 'Select Scale Z', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_rotate_x',
			'heading'     => esc_html__( 'Rotate X', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on X axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		   'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_rotate_y',
			'heading'     => esc_html__( 'Rotate Y', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on Y axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_rotate_z',
			'heading'     => esc_html__( 'Rotate Z', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on Z axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_init_opacity',
			'heading'     => esc_html__( 'Opacity', 'ruya' ),
			'description' => esc_html__( 'Set opacity', 'ruya' ),
			'min'         => 0,
			'max'         => 1,
			'step'        => 0.1,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		),

		//Animation Values
		array(
			'type'        => 'subheading',
			'param_name'  => 'ca_animations_values',
			'heading'     => esc_html__( 'Animate To', 'ruya' ),
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		),			
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_translate_x',
			'heading'     => esc_html__( 'Translate X', 'ruya' ),
			'description' => esc_html__( 'Select translate on X axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_translate_y',
			'heading'     => esc_html__( 'Translate Y', 'ruya' ),
			'description' => esc_html__( 'Select translate on Y axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_translate_z',
			'heading'     => esc_html__( 'Translate Z', 'ruya' ),
			'description' => esc_html__( 'Select translate on Z axe', 'ruya' ),
			'min'         => -500,
			'max'         => 500,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_scale_x',
			'heading'     => esc_html__( 'Scale X', 'ruya' ),
			'description' => esc_html__( 'Select Scale X', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_scale_y',
			'heading'     => esc_html__( 'Scale Y', 'ruya' ),
			'description' => esc_html__( 'Select Scale Y', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_scale_z',
			'heading'     => esc_html__( 'Scale Z', 'ruya' ),
			'description' => esc_html__( 'Select Scale Z', 'ruya' ),
			'min'         => 0,
			'max'         => 10,
			'step'        => 0.25,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_rotate_x',
			'heading'     => esc_html__( 'Rotate X', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on X axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_rotate_y',
			'heading'     => esc_html__( 'Rotate Y', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on Y axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_rotate_z',
			'heading'     => esc_html__( 'Rotate Z', 'ruya' ),
			'description' => esc_html__( 'Select rotate degree on Z axe', 'ruya' ),
			'min'         => -360,
			'max'         => 360,
			'step'        => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'        => 'mo_slider',
			'param_name'  => 'ca_an_opacity',
			'heading'     => esc_html__( 'Opacity', 'ruya' ),
			'description' => esc_html__( 'Set opacity', 'ruya' ),
			'min'         => 0,
			'max'         => 1,
			'step'        => 0.1,
			'std'         => 1,
			'group' => esc_html__( 'Animation', 'ruya' ),
			'dependency' => array(
				'element' => 'enable_split',
				'value'   => 'true',
			),
		),

	    
	   
	)
));